Update code in Screener.py and Database.py

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -3,7 +3,7 @@ name: Deploy
 on:
     pull_request:
         branches:
-            - prod-beta_block
+            - prod-beta
 jobs:
     run-tests:
         runs-on: ubuntu-latest
@@ -14,10 +14,11 @@ jobs:
 
         - name: Send rollout request
           run: |
-            curl -X POST \
+            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
             -H "Content-Type: application/json" \
             -d '{"key": "value"}' \
-            https://26b9-72-42-165-242.ngrok-free.app/rollout
-
-
-    
+            https://26b9-72-42-165-242.ngrok-free.app/rollout)
+            if [ "$response" -ne 200 ]; then
+              echo "Rollout failed with status code $response"
+              exit 1
+            fi
